name: deploy

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "functions/**"
      - "firebase.json"
      - ".github/workflows/deploy-functions.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Firebase CLI
        run: npm i -g firebase-tools@13

      - name: Write Service Account file
        run: |
          echo "$GCP_SA_KEY" > "${HOME}/sa.json"
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy ONLY selected functions (notify + onMensagemCreated)
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/sa.json
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        run: |
          firebase use "$FIREBASE_PROJECT_ID"
          # Garante que o deploy não pegue uma codebase antiga em Node 18:
          cat firebase.json
          # Suba só as funções já migradas para Node 20:
          firebase deploy --only "functions:notify,functions:onMensagemCreated" --force
