name: Deploy Firebase Functions

on:
  push:
    branches: [ main ]
    paths:
      - "functions/**"
      - ".firebaserc"
      - "firebase.json"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Install Firebase CLI
        run: npm i -g firebase-tools

      - name: Set functions runtime config (webpush)
        run: |
          firebase functions:config:set \
            webpush.public_key="${{ secrets.WEBPUSH_PUBLIC_KEY }}" \
            webpush.private_key="${{ secrets.WEBPUSH_PRIVATE_KEY }}" \
            webpush.subject="${{ secrets.WEBPUSH_SUBJECT }}" \
            --project gestao-chamados-stands
        # ↑ ajuste o project id se for diferente

      - name: Install Functions deps
        working-directory: functions
        run: npm ci

      - name: Deploy Functions
        run: firebase deploy --only functions --project gestao-chamados-stands
