name: deploy

on:
  push:
    branches: [ main ]
    paths:
      - "functions/**"
      - ".github/workflows/deploy-functions.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 20 (CLI)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Firebase CLI
        run: npm i -g firebase-tools@13

      - name: Write Service Account file
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" > $GITHUB_WORKSPACE/sa.json
          echo "Wrote SA to $GITHUB_WORKSPACE/sa.json"

      - name: Deploy ONLY selected functions (notify + onMensagemCreated)
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/sa.json
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        run: |
          firebase --project "$FIREBASE_PROJECT_ID" deploy \
            --only "functions:notify,functions:onMensagemCreated" \
            --force
