# .github/workflows/deploy-functions.yml (versão sem FCM key)
name: Deploy Firebase Functions

on:
  push:
    paths:
      - "functions/**"
      - ".github/workflows/deploy-functions.yml"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: functions/package-lock.json

      - name: Install Firebase CLI
        run: npm i -g firebase-tools

      - name: Install functions deps
        run: |
          cd functions
          npm ci

      - name: Set functions:config (apenas VAPID)
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID:     ${{ secrets.FIREBASE_PROJECT_ID }}
          VAPID_PUBLIC:   ${{ secrets.VAPID_PUBLIC_KEY }}
          VAPID_PRIVATE:  ${{ secrets.VAPID_PRIVATE_KEY }}
          VAPID_SUBJECT:  ${{ secrets.VAPID_SUBJECT }}
        run: |
          firebase functions:config:set \
            messaging.vapid_public_key="$VAPID_PUBLIC" \
            messaging.vapid_private_key="$VAPID_PRIVATE" \
            messaging.vapid_subject="$VAPID_SUBJECT" \
            --project "$PROJECT_ID" --token "$FIREBASE_TOKEN"

      - name: Deploy Functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID:     ${{ secrets.FIREBASE_PROJECT_ID }}
        run: |
          firebase deploy --only functions --project "$PROJECT_ID" --token "$FIREBASE_TOKEN"
