name: Deploy Firebase Functions (single)

on:
  workflow_dispatch:
    inputs:
      function_name:
        description: "Nome da função para deploy"
        default: "onMensagemCreated"
        required: true
  push:
    paths:
      - "functions/**"
      - "firebase.json"
      - ".firebaserc"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Firebase CLI
        run: npm i -g firebase-tools@13

      - name: Write Service Account to file
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}' > $HOME/gcp-sa.json

      - name: Deploy ONLY one function (Gen1)
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/gcp-sa.json
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        run: |
          firebase use "$FIREBASE_PROJECT_ID" --project "$FIREBASE_PROJECT_ID"
          firebase deploy --only "functions:${{ github.event.inputs.function_name || 'onMensagemCreated' }}" --force
