name: Deploy Cloud Functions

on:
  push:
    branches: [main]
    paths:
      - "functions/**"
      - ".github/workflows/deploy-functions.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      FIREBASE_PROJECT_ID: ${{ vars.FIREBASE_PROJECT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}

      - name: Install Firebase CLI
        run: npm i -g firebase-tools@13

      - name: Install Functions deps
        run: |
          cd functions
          npm ci || npm install

      - name: Deploy ONLY functions (notify + onMensagemCreated)
        run: |
          firebase deploy --only "functions:onMensagemCreated,functions:notify" \
            --project "$FIREBASE_PROJECT_ID" --force --non-interactive
