name: Deploy Firebase Functions

on:
  push:
    branches: [ "main" ]
    paths:
      - "functions/**"
      - "firebase.json"
      - ".github/workflows/deploy-functions.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Firebase CLI
        run: npm i -g firebase-tools

      - name: Install functions deps
        working-directory: functions
        run: npm ci

      # Se você quer definir as configs via CLI (recomendado)
      - name: Set functions:config (VAPID)
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          VAPID_SUBJECT: ${{ secrets.MESSAGING__VAPID_SUBJECT }}
          VAPID_PUBLIC: ${{ secrets.MESSAGING__VAPID_PUBLIC_KEY }}
          VAPID_PRIVATE: ${{ secrets.MESSAGING__VAPID_PRIVATE_KEY }}
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' > $HOME/gcp-key.json
          gcloud auth activate-service-account --key-file=$HOME/gcp-key.json
          firebase functions:config:set messaging.vapid_subject="$VAPID_SUBJECT" messaging.vapid_public_key="$VAPID_PUBLIC" messaging.vapid_private_key="$VAPID_PRIVATE" --project $FIREBASE_PROJECT_ID

      - name: Deploy Functions
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' > $HOME/gcp-key.json
          gcloud auth activate-service-account --key-file=$HOME/gcp-key.json
          firebase deploy --only functions --project $FIREBASE_PROJECT_ID --force
