name: Deploy Firebase Functions

on:
  workflow_dispatch:
  push:
    paths:
      - "functions/**"
      - ".github/workflows/deploy-functions.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Firebase CLI
        run: npm i -g firebase-tools@13

      - name: Inject .env for Functions
        working-directory: functions
        run: |
          cat > .env <<EOF
          WEBPUSH_SUBJECT=${{ secrets.WEBPUSH_SUBJECT }}
          WEBPUSH_PUBLIC_KEY=${{ secrets.WEBPUSH_PUBLIC_KEY }}
          WEBPUSH_PRIVATE_KEY=${{ secrets.WEBPUSH_PRIVATE_KEY }}
          EOF

      - name: Install Functions deps
        working-directory: functions
        run: npm ci || npm i

      - name: Deploy ONLY onMensagemCreated
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          # Se você usa service account JSON, troque por:
          # GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}
        run: |
          firebase use ${{ secrets.FIREBASE_PROJECT_ID }} --token "$FIREBASE_TOKEN"
          firebase deploy --only "functions:onMensagemCreated" --force --token "$FIREBASE_TOKEN"
