name: Deploy Firebase Functions (v2 + Secrets)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      # Gatilhos originais:
      - "functions/**"
      - ".github/workflows/deploy-functions.yml"
      # ⬇️ GATILHO ADICIONADO:
      - "firebase.json"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Firebase CLI
        run: npm i -g firebase-tools@13

      - name: Install Functions deps
        run: |
          cd functions
          npm install --no-audit --no-fund
          cd ..

      - name: Set Firebase Secrets (VAPID)
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          WEBPUSH_PRIVATE_KEY: ${{ secrets.WEBPUSH_PRIVATE_KEY }}
          WEBPUSH_PUBLIC_KEY:  ${{ secrets.WEBPUSH_PUBLIC_KEY }}
          WEBPUSH_SUBJECT:     ${{ secrets.WEBPUSH_SUBJECT }}
        run: |
          echo "$WEBPUSH_PRIVATE_KEY" | firebase functions:secrets:set WEBPUSH_PRIVATE_KEY --project "$FIREBASE_PROJECT_ID" --non-interactive
          echo "$WEBPUSH_PUBLIC_KEY" | firebase functions:secrets:set WEBPUSH_PUBLIC_KEY --project "$FIREBASE_PROJECT_ID" --non-interactive
          echo "$WEBPUSH_SUBJECT" | firebase functions:secrets:set WEBPUSH_SUBJECT --project "$FIREBASE_PROJECT_ID" --non-interactive

      - name: Deploy ALL Functions (v2)
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        run: |
          firebase deploy --only functions --project "$FIREBASE_PROJECT_ID" --non-interactive --force
